name: node-coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "13 16 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - name: Set git to use LF to checkout
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        run: npm install
        env:
          CI: true

      - run: bash install_no_trace_deps.sh

      - run: npm run build --if-present

      - name: test & coverage
        run: npm run coverage

      - name: upload coverage
        uses: codecov/codecov-action@v4
