name: security-scan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "3 5 * * *"

jobs:
  security-scan:

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v1
      
      - run: npm ci

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master